// <auto-generated />
using System;
using ContosoHotels.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ContosoHotels.Migrations
{
    [DbContext(typeof(ContosoHotelsContext))]
    [Migration("20250605182315_UpdateRoomDefaultCities")]
    partial class UpdateRoomDefaultCities
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            // The remainder of this file would be auto-generated with the model definition
            // This is a placeholder file to match the migration
#pragma warning restore 612, 618
        }
    }
}
